# Generated by Django 4.2.1 on 2023-05-24 03:29

# Standard Libraries
import uuid

# Django Imports
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.PositiveSmallIntegerField(choices=[(0, "HTTP"), (1, "SSH")]),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("observation", models.TextField(blank=True, null=True)),
                ("is_disable", models.BooleanField(default=False)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select explicit allowed users for this access",
                        related_name="allowed_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "denied_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select explicit denied users for this access",
                        related_name="denied_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Accesses",
            },
        ),
    ]
