# Generated by Django 4.2.1 on 2023-05-27 03:51

# Django Imports
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0002_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select explicit allowed users for this access",
                related_name="accesses_allowed_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="access",
            name="denied_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select explicit denied users for this access",
                related_name="accesses_denied_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_disable", models.BooleanField(default=False)),
                (
                    "accesses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select accesses for this policy",
                        related_name="policies_access",
                        to="console.access",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select users for this policy",
                        related_name="policies_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
