# Generated by Django 4.2.1 on 2023-05-27 04:02

# Django Imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "console",
            "0003_alter_access_allowed_users_alter_access_denied_users_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name_plural": "policies"},
        ),
    ]
